Task implementation
OpusCapita/bnp pull request #258
Opened 2020-08-31 09:54 UTC by jacekWojcikOpusCapita

Merge SupplierInformation and BuyerInformation forms to BusinessPartnerInformation

https://opuscapita.atlassian.net/browse/BPR-5218

2020-08-31 10:10 UTC, jaconsta requested changes
Please leave the routing out of this PR scope. And adjust to the naming conventions.

2020-08-31 10:10 UTC, jaconsta commented on src/client/containers/Main.react.js
>  import { Route } from 'react-router';
Please, remove this file from the PR

2020-08-31 10:10 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +            bpId: this.context.userData.businesspartnerid
Can you please explain which cases the businessPartnerId is `undefined`? And for those, what backwards compatibility is required (ex using the old userData.customerId, userData.supplierId)?

2020-08-31 10:10 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +      this.context.setPageTitle(i18n.getMessage('BusinessPartnerInformation.page.title'));
can you add the function to the this.context, object destructuring above?

2020-08-31 10:10 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +    state = { tabKey: this.props.location.query.tab || 'company' };
can you add the businessPartnerId to the initial state declaration.

I understand we talked about using `bpId` instead of `businessPartnerId`. But if you look to the naming the components already use `businessPartnerId` so please, let's keep the convention and use the full name.

2020-08-31 10:10 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> + * BP - business partner
This won't be needed anymore.

2020-08-31 10:47 UTC, jacekWojcikOpusCapita commented on src/client/containers/Main.react.js
>  import { Route } from 'react-router';
Done

2020-08-31 10:56 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +      this.context.setPageTitle(i18n.getMessage('BusinessPartnerInformation.page.title'));
Done.

2020-08-31 10:56 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +    state = { tabKey: this.props.location.query.tab || 'company' };
Done.

2020-08-31 10:57 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> + * BP - business partner
Done.

2020-08-31 12:12 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +            bpId: this.context.userData.businesspartnerid
Added relevant comments.

2020-09-04 14:34 UTC, jaconsta requested changes
Nice work!!!
Please make the suggested changes.

2020-09-04 14:34 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +        // this value is taken from `User` table, so it depends on data in the database
Do you know how many users will be affected by this condition?

2020-09-04 14:34 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +            businessPartnerId: this.context.userData.businesspartnerid
Why set the businessPartnerId in the state if this value is not going to mutate in the component lifecycle?

2020-09-04 14:34 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +      this.isDirty = event.isDirty;
Can you test the possibility to assign the `ìsDirty` property to the state instead of the class attribute?

2020-09-04 14:34 UTC, jaconsta commented on src/client/containers/i18n/en.json
>              "title": "Buyer dashboard"
Can you help me with the Polish translations, and please adjust the Spanish translations file schema so I can update the text on those.

2020-09-04 14:36 UTC, jaconsta requested changes

2020-09-04 14:36 UTC, jaconsta commented on src/client/containers/BusinessPartnerInformation.js
> +  export default BusinessPartnerInformation;
Please add the empty line at the end of the file.

2020-09-11 10:28 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +        // this value is taken from `User` table, so it depends on data in the database
I think that we need to make sure
once we do not have `supplierId` nor `customerId` in the `User` table, 
that `businessPartnerId` is populated

if so, none of the users will be affected

2020-09-11 10:36 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +  export default BusinessPartnerInformation;
Done.

2020-09-11 10:41 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +            businessPartnerId: this.context.userData.businesspartnerid
Replaced all occurrences of `this.state.businessPartnerId` with `this.businessPartnerId`.

2020-09-11 10:43 UTC, jacekWojcikOpusCapita commented on src/client/containers/BusinessPartnerInformation.js
> +      this.isDirty = event.isDirty;
Replaced line 83 with `this.setState({isDirty : event.isDirty});`

2020-09-11 13:55 UTC, jacekWojcikOpusCapita commented on src/client/containers/i18n/en.json
>              "title": "Buyer dashboard"
Changed schema of Spanish translation, 
can help you with the Polish one but maybe once you have this task finished and then I will take care of translations?

2020-09-14 07:13 UTC, merged