Feature/bpr 5219 business partner information
OpusCapita/bnp pull request #260
Opened 2020-09-04 08:05 UTC by jacekWojcikOpusCapita

Handle the BusinessPartnerInformation route component rendering.
https://opuscapita.atlassian.net/browse/BPR-5219

**Short description**

_We have two endpoints (showing almost identical information):_

SupplierInformation : https://businessnetwork.opuscapita.com/bnp/supplierInformation#
BuyerInformation : https://businessnetwork.opuscapita.com/bnp/buyerInformation#

_We want to have only one endpoint_:

-> BusinessPartnerInformation: https://businessnetwork.opuscapita.com/bnp/businessPartnerInformation#

2020-09-04 14:57 UTC, jaconsta requested changes
Thanks for facilitating the completeness.

2020-09-11 11:16 UTC, maciej-wakula-opuscapita commented on src/client/containers/Main.react.js
> +                <Redirect from="/buyerInformation" to="/businessPartnerInformation" />
Hi
I have verified - both /supplierInformation?whatever=value and /buyerInformation?whatever=value are redirecting to /businessPartnerInformation?whatever=value

2020-09-11 11:16 UTC, maciej-wakula-opuscapita commented on .eslintrc.json
> +{
I have removed the eslint entirely from this branch

2020-09-11 11:16 UTC, maciej-wakula-opuscapita commented
The pull request is failing tests as I have not added businessPartnerInformation (as requested) - although I have it available on my computer so just let me know if I should upload it as well

2020-09-14 07:14 UTC, merged